### ISSUE TITLE
Production ready? (missing service control, config yaml)

### ISSUE THREAD

**Issue by chook** [andrewrothstein/ansible-opentelemetry_collector#1]
Thanks @andrewrothstein for this project!

I found this repo on galaxy (as compared to the splunk bloated one) and it does seem like a good "start" but i wonder if my lack of Ansible knowledge hides necessary parts such as a systemd / service control that will make sure the collector will always be running.

Also, when rolling this out, where the config.yaml is expected to reside?

**Comment by andrewrothstein** [comment]
this role installs the binaries. configuring the collector and the process supervision is left as an exercise for the user. I’m open to a PR that adds/enables a more full fledged ansible based deployment/production grade configuration if ur planning to build that out atop this role.

**Comment by chook** [comment]
Thanks Andrew for replying! I'll resurface this if we'll end up doing so
